name: 💡 Suggestion
description: Propose a new exercise, module, or improvement.
title: "[Idea]: <Short Description>"
labels: ["enhancement", "idea"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: What would you like to see added or improved?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Why is this important? Who would it help?
